name: Build Godot Game for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Print working directory
      run: pwd

    - name: List directory contents
      run: ls -la

    - name: build godot
      id: export
      uses: firebelley/godot-export@v5.2.0
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true


    - name: Build project
      run: godot --export "Windows Desktop" ./project.godot

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-export
        path: ${{ steps.export.outputs.archive_directory }}  # Ruta del build exportado para Windows
