name: Build Godot Game for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Godot
      uses: firebelley/godot-export@v5.2.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_32.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true
        archive_root_folder: false
        cache: false
        use_preset_export_path: false
        export_debug: false
        verbose: false
        use_godot_3: false
        export_as_pack: false

    - name: Build
      run: |
        ./home/runner/.local/share/godot/godot_executable/Godot_v4.3-stable_linux.x86_32 --export "YourExportPreset" "YourOutputFile.exe"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-export
        path: ${{ steps.export.outputs.archive_directory }}  # Ruta del build exportado para Windows
